name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: ZAP Scan
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Introduce a rate limit here
          sleep 60  # Sleep for 60 seconds (adjust as needed)
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ${DOCKER_USERNAME}/zap-baseline -t http://testphp.vulnweb.com/ -c .zap/rules.tsv
